// GENERATED by scripts/build-data.mjs from data/*.csv — do not edit by hand.
// Georgia: confirmed against the November 2026 sale deadline report (Sept 2026).
// South Carolina: compiled April 2022, partially checked; see data/VERIFICATION.md.
export const DATA_COMPILED = { Georgia: '2026-09', 'South Carolina': '2022-04' };
export default [
 {
  "name": "Georgia",
  "counties": [
   {
    "name": "Fulton",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 9,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week prior @ 12:00 (9 days prior @ 12pm)"
    }
   },
   {
    "name": "Butts",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 9,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week prior @ 12:00 (9 days prior @ 12pm)"
    }
   },
   {
    "name": "Clayton",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 9,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week prior @ 12:00 (9 days prior @ 12pm)"
    }
   },
   {
    "name": "Gwinnett",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 9,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week prior @ 12:00 (9 days prior @ 12pm)"
    }
   },
   {
    "name": "Henry",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 9,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week prior @ 12:00 (9 days prior @ 12pm)"
    }
   },
   {
    "name": "Rockdale",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 9,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week prior @ 12:00 (9 days prior @ 12pm)"
    }
   },
   {
    "name": "Douglas",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 8,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "tuesday Week prior @ 4:00 (8 days prior @ 4pm)"
    }
   },
   {
    "name": "Columbia",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 7,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "wednesday Week prior @ 3:00 (7 days prior @ 3pm)"
    }
   },
   {
    "name": "Murray",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 7,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "wednesday Week prior @ 5:00 (7 days prior @ 5pm)"
    }
   },
   {
    "name": "Johnson",
    "publicationDays": [
     "Tuesday"
    ],
    "deadlines": {
     "Tuesday": {
      "daysPrior": 6,
      "time": "9am"
     }
    },
    "source": {
     "publicationDay": "Tuesday",
     "deadline": "wednesday Week prior @ 9:00 (6 days prior @ 9am)"
    }
   },
   {
    "name": "Banks",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "wednesday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Barrow",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "wednesday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Dekalb",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 8,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "wednesday Week prior @ 12:00 (8 days prior @ 12pm)"
    }
   },
   {
    "name": "Jackson",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "wednesday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Madison",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "wednesday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Oconee",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 3:00 (7 days prior @ 3pm)"
    }
   },
   {
    "name": "Worth",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 3:00 (6 days prior @ 3pm)"
    }
   },
   {
    "name": "Bleckley",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 4:00 (7 days prior @ 4pm)"
    }
   },
   {
    "name": "Burke",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 4:00 (6 days prior @ 4pm)"
    }
   },
   {
    "name": "Carroll",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 4:00 (7 days prior @ 4pm)"
    }
   },
   {
    "name": "Dade",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 4:00 (6 days prior @ 4pm)"
    }
   },
   {
    "name": "Early",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 4:00 (6 days prior @ 4pm)"
    }
   },
   {
    "name": "Glascock",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 4:00 (7 days prior @ 4pm)"
    }
   },
   {
    "name": "Haralson",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 4:00 (7 days prior @ 4pm)"
    }
   },
   {
    "name": "Jefferson",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 4:00 (7 days prior @ 4pm)"
    }
   },
   {
    "name": "Richmond",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 4:00 (7 days prior @ 4pm)"
    }
   },
   {
    "name": "Twiggs",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 4:00 (7 days prior @ 4pm)"
    }
   },
   {
    "name": "Bartow",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 5:00 (7 days prior @ 5pm)"
    }
   },
   {
    "name": "Catoosa",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Jenkins",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Polk",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Walker",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Lamar",
    "publicationDays": [
     "Tuesday"
    ],
    "deadlines": {
     "Tuesday": {
      "daysPrior": 5,
      "time": "10am"
     }
    },
    "source": {
     "publicationDay": "Tuesday",
     "deadline": "thursday Week prior @ 10:00 (5 days prior @ 10am)"
    }
   },
   {
    "name": "Candler",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Clay",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Colquitt",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Dawson",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Fannin",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Forsyth",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Hall",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Houston",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "McIntosh",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Miller",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Muscogee",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Pike",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Pulaski",
    "publicationDays": [
     "Tuesday"
    ],
    "deadlines": {
     "Tuesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Tuesday",
     "deadline": "thursday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Thomas",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Tift",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Turner",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "thursday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Wilkinson",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "thursday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Crisp",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "1pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 1:00 (5 days prior @ 1pm)"
    }
   },
   {
    "name": "Gilmer",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "2pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 2:00 (5 days prior @ 2pm)"
    }
   },
   {
    "name": "Clinch",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 3:00 (5 days prior @ 3pm)"
    }
   },
   {
    "name": "Lanier",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 3:00 (5 days prior @ 3pm)"
    }
   },
   {
    "name": "Lumpkin",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 3:00 (5 days prior @ 3pm)"
    }
   },
   {
    "name": "Appling",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 4:00 (5 days prior @ 4pm)"
    }
   },
   {
    "name": "Brantley",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 4:00 (5 days prior @ 4pm)"
    }
   },
   {
    "name": "Charlton",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 4:00 (5 days prior @ 4pm)"
    }
   },
   {
    "name": "Hancock",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 4:00 (5 days prior @ 4pm)"
    }
   },
   {
    "name": "Spalding",
    "publicationDays": [
     "Saturday"
    ],
    "deadlines": {
     "Saturday": {
      "daysPrior": 8,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Saturday",
     "deadline": "friday Week prior @ 4:00 (8 days prior @ 4pm)"
    }
   },
   {
    "name": "Towns",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 4:00 (5 days prior @ 4pm)"
    }
   },
   {
    "name": "Union",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 4:00 (5 days prior @ 4pm)"
    }
   },
   {
    "name": "Bacon",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Baldwin",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Berrien",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Chatham",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Dodge",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Dooly",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Emanuel",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Gordon",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Heard",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Jasper",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Lee",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Liberty",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Lincoln",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Macon",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "Morgan",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Pierce",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 5:00 (5 days prior @ 5pm)"
    }
   },
   {
    "name": "White",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Wilkes",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 5:00 (6 days prior @ 5pm)"
    }
   },
   {
    "name": "Decatur",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "9am"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 9:00 (5 days prior @ 9am)"
    }
   },
   {
    "name": "Treutlen",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "9am"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 9:00 (6 days prior @ 9am)"
    }
   },
   {
    "name": "Upson",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "10am"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 10:00 (5 days prior @ 10am)"
    }
   },
   {
    "name": "Baker",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Ben Hill",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Bibb",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Brooks",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Cherokee",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Cobb",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "friday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Cook",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Coweta",
    "publicationDays": [
     "Saturday"
    ],
    "deadlines": {
     "Saturday": {
      "daysPrior": 8,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Saturday",
     "deadline": "friday Week prior @ 12:00 (8 days prior @ 12pm)"
    }
   },
   {
    "name": "Crawford",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Echols",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Fayette",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Grady",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Greene",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Habersham",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Harris",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Irwin",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Lowndes",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "McDuffie",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Meriwether",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Mitchell",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Monroe",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Paulding",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Peach",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Pickens",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Putnam",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Talbot",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "friday Week prior @ 12:00 (6 days prior @ 12pm)"
    }
   },
   {
    "name": "Taliaferro",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "friday Week prior @ 12:00 (7 days prior @ 12pm)"
    }
   },
   {
    "name": "Ware",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Washington",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "friday Week prior @ 12:00 (5 days prior @ 12pm)"
    }
   },
   {
    "name": "Wilcox",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "3:30pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 3:30 (2 days prior @ 3:30pm)"
    }
   },
   {
    "name": "Franklin",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 4:00 (3 days prior @ 4pm)"
    }
   },
   {
    "name": "Camden",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "4:30pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 4:30 (3 days prior @ 4:30pm)"
    }
   },
   {
    "name": "Chattahoochee",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 5:00 (2 days prior @ 5pm)"
    }
   },
   {
    "name": "Jeff Davis",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 5:00 (2 days prior @ 5pm)"
    }
   },
   {
    "name": "Marion",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 5:00 (2 days prior @ 5pm)"
    }
   },
   {
    "name": "Randolph",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 5:00 (2 days prior @ 5pm)"
    }
   },
   {
    "name": "Schley",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 5:00 (3 days prior @ 5pm)"
    }
   },
   {
    "name": "Screven",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 5:00 (2 days prior @ 5pm)"
    }
   },
   {
    "name": "Seminole",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 5:00 (3 days prior @ 5pm)"
    }
   },
   {
    "name": "Stewart",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 5:00 (3 days prior @ 5pm)"
    }
   },
   {
    "name": "Terrell",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 5:00 (3 days prior @ 5pm)"
    }
   },
   {
    "name": "Webster",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 5:00 (3 days prior @ 5pm)"
    }
   },
   {
    "name": "Sumter",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "9am"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 9:00 (2 days prior @ 9am)"
    }
   },
   {
    "name": "Walton",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "9am"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 9:00 (2 days prior @ 9am)"
    }
   },
   {
    "name": "Atkinson",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Coffee",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Effingham",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Elbert",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Evans",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Hart",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Jones",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Montgomery",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Oglethorpe",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Rabun",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Stephens",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Taylor",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Telfair",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Toombs",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Wayne",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "monday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Wheeler",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "monday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Warren",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 2,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "tuesday Week of @ 5:00 (2 days prior @ 5pm)"
    }
   },
   {
    "name": "Bryan",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "tuesday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Bulloch",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "tuesday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Chattooga",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "tuesday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Floyd",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "tuesday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Long",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "tuesday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Quitman",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 1,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "tuesday Week of @ 12:00 (1 day prior @ 12pm)"
    }
   },
   {
    "name": "Tattnall",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "tuesday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Calhoun",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "wednesday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Clarke",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "wednesday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Dougherty",
    "publicationDays": [
     "Saturday"
    ],
    "deadlines": {
     "Saturday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Saturday",
     "deadline": "wednesday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Newton",
    "publicationDays": [
     "Saturday"
    ],
    "deadlines": {
     "Saturday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Saturday",
     "deadline": "wednesday Week of @ 12:00 (3 days prior @ 12pm)"
    }
   },
   {
    "name": "Whitfield",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "wednesday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   },
   {
    "name": "Troup",
    "publicationDays": [
     "Saturday"
    ],
    "deadlines": {
     "Saturday": {
      "daysPrior": 2,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Saturday",
     "deadline": "thursday Week of @ 5:00 (2 days prior @ 5pm)"
    }
   },
   {
    "name": "Laurens",
    "publicationDays": [
     "Saturday"
    ],
    "deadlines": {
     "Saturday": {
      "daysPrior": 2,
      "time": "9:30am"
     }
    },
    "source": {
     "publicationDay": "Saturday",
     "deadline": "thursday Week of @ 9:30 (2 days prior @ 9:30am)"
    }
   },
   {
    "name": "Glynn",
    "publicationDays": [
     "Saturday"
    ],
    "deadlines": {
     "Saturday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Saturday",
     "deadline": "thursday Week of @ 12:00 (2 days prior @ 12pm)"
    }
   }
  ]
 },
 {
  "name": "South Carolina",
  "counties": [
   {
    "name": "Abbeville",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "2 days prior @ 5pm"
    }
   },
   {
    "name": "Aiken",
    "publicationDays": [
     "Monday",
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday",
     "Sunday"
    ],
    "deadlines": {
     "Monday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Tuesday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Wednesday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Thursday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Friday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Saturday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Sunday": {
      "daysPrior": 3,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Daily",
     "deadline": "3 days prior @ 4pm"
    }
   },
   {
    "name": "Allendale",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "5 days prior @ 12pm"
    }
   },
   {
    "name": "Anderson",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "5 days prior @ 12pm"
    }
   },
   {
    "name": "Bamberg",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "2 days prior @ 12pm"
    }
   },
   {
    "name": "Barnwell",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "5 days prior @ 12pm"
    }
   },
   {
    "name": "Beaufort",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 1,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "1 day prior @ 12pm"
    }
   },
   {
    "name": "Berkeley",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "5 days prior @ 4pm"
    }
   },
   {
    "name": "Calhoun",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "2 days prior @ 12pm"
    }
   },
   {
    "name": "Charleston",
    "publicationDays": [
     "Monday",
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday",
     "Sunday"
    ],
    "deadlines": {
     "Tuesday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Friday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Saturday": {
      "daysPrior": 2,
      "time": "4pm"
     },
     "Sunday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Monday": {
      "daysPrior": 4,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Daily",
     "deadline": "Tuesday-Friday: 2 days prior @ 12pm / Saturday-Monday: Thursday @ 4pm"
    }
   },
   {
    "name": "Cherokee",
    "publicationDays": [
     "Monday",
     "Wednesday",
     "Friday"
    ],
    "deadlines": {
     "Monday": {
      "daysPrior": 7,
      "time": "12pm"
     },
     "Wednesday": {
      "daysPrior": 7,
      "time": "12pm"
     },
     "Friday": {
      "daysPrior": 7,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Monday, Wednesday, Friday",
     "deadline": "7 days prior @ 12pm"
    }
   },
   {
    "name": "Chester",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "2 days prior @ 3pm"
    }
   },
   {
    "name": "Chesterfield",
    "publicationDays": [
     "Tuesday"
    ],
    "deadlines": {
     "Tuesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Tuesday",
     "deadline": "6 days prior @ 12 pm"
    }
   },
   {
    "name": "Clarendon",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "6 days prior @ 12 pm"
    }
   },
   {
    "name": "Colleton",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "2pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "6 days prior @ 2 pm"
    }
   },
   {
    "name": "Darlington",
    "publicationDays": [
     "Wednesday",
     "Friday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     },
     "Friday": {
      "daysPrior": 3,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday, Friday",
     "deadline": "Wednesday: 5 days prior @ 5 pm / Friday: 3 days prior @ 5 pm"
    }
   },
   {
    "name": "Dillon",
    "publicationDays": [
     "Tuesday",
     "Thursday"
    ],
    "deadlines": {
     "Tuesday": {
      "daysPrior": 1,
      "time": "11am"
     },
     "Thursday": {
      "daysPrior": 1,
      "time": "11am"
     }
    },
    "source": {
     "publicationDay": "Tuesday, Thursday",
     "deadline": "1 day prior @ 11am"
    }
   },
   {
    "name": "Dorchester",
    "publicationDays": [
     "Monday",
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday",
     "Sunday"
    ],
    "deadlines": {
     "Tuesday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Friday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Saturday": {
      "daysPrior": 2,
      "time": "4pm"
     },
     "Sunday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Monday": {
      "daysPrior": 4,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Daily",
     "deadline": "Tuesday-Friday: 2 days prior @ 12 pm / Saturday-Monday: Thursday @ 4 pm"
    }
   },
   {
    "name": "Edgefield",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 6,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "6 days prior @ 12 pm"
    }
   },
   {
    "name": "Fairfield",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "3 days prior @ 12 pm"
    }
   },
   {
    "name": "Florence",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 4,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "4 days prior @ 12 pm"
    }
   },
   {
    "name": "Georgetown",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "11am"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "2 days prior @ 11 am"
    }
   },
   {
    "name": "Greenville",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 8,
      "time": "10am"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "8 days prior @ 10 am"
    }
   },
   {
    "name": "Greenwood",
    "publicationDays": [
     "Monday",
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday",
     "Sunday"
    ],
    "deadlines": {
     "Monday": {
      "daysPrior": 3,
      "time": "5pm"
     },
     "Tuesday": {
      "daysPrior": 3,
      "time": "5pm"
     },
     "Wednesday": {
      "daysPrior": 3,
      "time": "5pm"
     },
     "Thursday": {
      "daysPrior": 3,
      "time": "5pm"
     },
     "Friday": {
      "daysPrior": 3,
      "time": "5pm"
     },
     "Saturday": {
      "daysPrior": 3,
      "time": "5pm"
     },
     "Sunday": {
      "daysPrior": 3,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Daily",
     "deadline": "3 days prior @ 5pm"
    }
   },
   {
    "name": "Hampton",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "3 days prior @ 12 pm"
    }
   },
   {
    "name": "Horry",
    "publicationDays": [
     "Monday",
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday",
     "Sunday"
    ],
    "deadlines": {
     "Monday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Tuesday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Wednesday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Thursday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Friday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Saturday": {
      "daysPrior": 3,
      "time": "4pm"
     },
     "Sunday": {
      "daysPrior": 3,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Daily",
     "deadline": "3 days prior @ 4 pm"
    },
    "warnings": [
     "If this row means The Sun News, it has printed only twice weekly since June 2024, not daily"
    ]
   },
   {
    "name": "Jasper",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 1,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "1 day prior @ 12 pm"
    }
   },
   {
    "name": "Kershaw",
    "publicationDays": [
     "Monday",
     "Wednesday",
     "Friday"
    ],
    "deadlines": {
     "Monday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Friday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Monday, Wednesday, Friday",
     "deadline": "2 days prior @ 12 pm"
    }
   },
   {
    "name": "Lancaster",
    "publicationDays": [
     "Sunday",
     "Wednesday"
    ],
    "deadlines": {
     "Sunday": {
      "daysPrior": 3,
      "time": "3pm"
     },
     "Wednesday": {
      "daysPrior": 3,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Sunday, Wednesday",
     "deadline": "3 days prior @ 3 pm"
    }
   },
   {
    "name": "Laurens",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 7,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "7 days prior @ 5pm"
    }
   },
   {
    "name": "Lee",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "5 days prior @ 4 pm"
    }
   },
   {
    "name": "Lexington",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 6,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "6 days prior @ 5 pm"
    }
   },
   {
    "name": "McCormick",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "3 days prior @ 12 pm"
    }
   },
   {
    "name": "Marion",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "11am"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "2 days prior @ 11 am"
    }
   },
   {
    "name": "Marlboro",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "2 days prior @ 12 pm"
    }
   },
   {
    "name": "Newberry",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "4pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "2 days prior @ 4 pm"
    }
   },
   {
    "name": "Oconee",
    "publicationDays": [
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday"
    ],
    "deadlines": {
     "Tuesday": {
      "daysPrior": 1,
      "time": "12pm"
     },
     "Wednesday": {
      "daysPrior": 1,
      "time": "12pm"
     },
     "Thursday": {
      "daysPrior": 1,
      "time": "12pm"
     },
     "Friday": {
      "daysPrior": 1,
      "time": "12pm"
     },
     "Saturday": {
      "daysPrior": 1,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Tuesday, Wednesday, Thursday, Friday, Saturday",
     "deadline": "1 day prior @ 12 pm"
    }
   },
   {
    "name": "Orangeburg",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "3 days prior @ 12 pm"
    }
   },
   {
    "name": "Pickens",
    "publicationDays": [
     "Wednesday",
     "Saturday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "3pm"
     },
     "Saturday": {
      "daysPrior": 2,
      "time": "3pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday, Saturday",
     "deadline": "2 days prior @ 3 pm"
    }
   },
   {
    "name": "Richland",
    "publicationDays": [
     "Monday",
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday",
     "Sunday"
    ],
    "deadlines": {
     "Monday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Tuesday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Wednesday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Thursday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Friday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Saturday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Sunday": {
      "daysPrior": 2,
      "time": "1pm"
     }
    },
    "source": {
     "publicationDay": "Daily",
     "deadline": "2 days prior @ 1 pm"
    },
    "warnings": [
     "If this row means The State, it has printed only Wednesday, Friday and Sunday since April 2024, not daily"
    ]
   },
   {
    "name": "Saluda",
    "publicationDays": [
     "Monday",
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday",
     "Sunday"
    ],
    "deadlines": {
     "Monday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Tuesday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Wednesday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Thursday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Friday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Saturday": {
      "daysPrior": 2,
      "time": "1pm"
     },
     "Sunday": {
      "daysPrior": 2,
      "time": "1pm"
     }
    },
    "source": {
     "publicationDay": "Daily",
     "deadline": "2 days prior @ 1 pm"
    },
    "warnings": [
     "If this row means The State, it has printed only Wednesday, Friday and Sunday since April 2024, not daily"
    ]
   },
   {
    "name": "Spartanburg",
    "publicationDays": [
     "Thursday"
    ],
    "deadlines": {
     "Thursday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Thursday",
     "deadline": "3 days prior @ 12 pm"
    }
   },
   {
    "name": "Sumter",
    "publicationDays": [
     "Friday"
    ],
    "deadlines": {
     "Friday": {
      "daysPrior": 3,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Friday",
     "deadline": "3 days prior @ 12 pm"
    }
   },
   {
    "name": "Union",
    "publicationDays": [
     "Wednesday",
     "Friday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 2,
      "time": "12pm"
     },
     "Friday": {
      "daysPrior": 2,
      "time": "12pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday, Friday",
     "deadline": "2 days prior @ 12 pm"
    }
   },
   {
    "name": "Williamsburg",
    "publicationDays": [
     "Wednesday"
    ],
    "deadlines": {
     "Wednesday": {
      "daysPrior": 5,
      "time": "5pm"
     }
    },
    "source": {
     "publicationDay": "Wednesday",
     "deadline": "5 days prior @ 5 pm"
    }
   },
   {
    "name": "York",
    "publicationDays": [
     "Monday",
     "Tuesday",
     "Wednesday",
     "Thursday",
     "Friday",
     "Saturday",
     "Sunday"
    ],
    "deadlines": {
     "Monday": {
      "daysPrior": 3,
      "time": "2pm"
     },
     "Tuesday": {
      "daysPrior": 3,
      "time": "2pm"
     },
     "Wednesday": {
      "daysPrior": 3,
      "time": "2pm"
     },
     "Thursday": {
      "daysPrior": 3,
      "time": "2pm"
     },
     "Friday": {
      "daysPrior": 3,
      "time": "2pm"
     },
     "Saturday": {
      "daysPrior": 3,
      "time": "2pm"
     },
     "Sunday": {
      "daysPrior": 3,
      "time": "2pm"
     }
    },
    "source": {
     "publicationDay": "Daily",
     "deadline": "3 days prior @ 2 pm"
    },
    "warnings": [
     "If this row means The Herald (Rock Hill), it has printed only Wednesday, Friday and Sunday since July 2024, not daily"
    ]
   }
  ]
 }
];
